---
# tasks file for nginx


- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install Docker
  package:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-python

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create /nginx build directory
  file:
    path: /nginx
    state: directory
    mode: '755'

- name: Copy docker files
  copy:
    src: "{{ item }}"
    dest: /nginx
    owner: root
    group: root
    mode: '0644'
  loop:
    - Dockerfile
    - lb.conf

- name: Build nginx container
  docker_image:
    name: lb
    state: present
    source: build
    build:
      path: /nginx
      pull: yes
      dockerfile: /nginx/Dockerfile 

      

- name: Run nginx container
  docker_container:
    name: lb
    image: lb
    state: started
    published_ports:
      - 80:80

#- name: Run nginx container
#  command: docker run --name nginx -p 80:80 -d nginx  
